/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NCode: typeof import('naive-ui')['NCode']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NP: typeof import('naive-ui')['NP']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const NAlert: typeof import('naive-ui')['NAlert']
  const NButton: typeof import('naive-ui')['NButton']
  const NButtonGroup: typeof import('naive-ui')['NButtonGroup']
  const NCard: typeof import('naive-ui')['NCard']
  const NCode: typeof import('naive-ui')['NCode']
  const NCollapse: typeof import('naive-ui')['NCollapse']
  const NCollapseItem: typeof import('naive-ui')['NCollapseItem']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDatePicker: typeof import('naive-ui')['NDatePicker']
  const NFlex: typeof import('naive-ui')['NFlex']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
  const NH1: typeof import('naive-ui')['NH1']
  const NH2: typeof import('naive-ui')['NH2']
  const NH3: typeof import('naive-ui')['NH3']
  const NInput: typeof import('naive-ui')['NInput']
  const NInputNumber: typeof import('naive-ui')['NInputNumber']
  const NMenu: typeof import('naive-ui')['NMenu']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NP: typeof import('naive-ui')['NP']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NSwitch: typeof import('naive-ui')['NSwitch']
  const NTag: typeof import('naive-ui')['NTag']
  const NText: typeof import('naive-ui')['NText']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}